server:
  port: 8080

#配置RabbitMQ
spring:
  rabbitmq:
    host: 127.0.0.1
    username: guest
    password: guest
    port: 5672

    #发布消息 交换机回调函数
    publisher-confirm-type: correlated
    #发布消息 失败回退消息
    publisher-returns: true